export const mockExercises = [
  {
    id: 3,
    name: "Barbell Back Squat",
    primaryMuscleGroup: "BACK",
    equipment: "BARBELL",
    type: "STRENGTH",
    isCustom: true,
    isActive: true,
    createdAt: "2026-02-16T22:49:51.080Z",
    updatedAt: "2026-02-17T02:28:52.651Z",
  },
  {
    id: 1,
    name: "Barbell Back Squat (Heavy)",
    primaryMuscleGroup: "QUADS",
    equipment: "BARBELL",
    type: "STRENGTH",
    isCustom: true,
    isActive: false,
    createdAt: "2026-02-16T22:49:50.583Z",
    updatedAt: "2026-02-17T03:18:44.485Z",
  },
  {
    id: 2,
    name: "Barbell Bench Press",
    primaryMuscleGroup: "CHEST",
    equipment: "BARBELL",
    type: "STRENGTH",
    isCustom: false,
    isActive: true,
    createdAt: "2026-02-16T22:49:51.007Z",
    updatedAt: "2026-02-16T22:52:57.951Z",
  },
  {
    id: 23,
    name: "Cable Bicep Curl",
    primaryMuscleGroup: "BICEPS",
    equipment: "CABLE",
    type: "STRENGTH",
    isCustom: true,
    isActive: true,
    createdAt: "2026-02-17T02:02:18.604Z",
    updatedAt: "2026-02-17T02:02:18.604Z",
  },
  {
    id: 5,
    name: "Dumbbell Shoulder Press",
    primaryMuscleGroup: "SHOULDERS",
    equipment: "DUMBBELL",
    type: "STRENGTH",
    isCustom: false,
    isActive: true,
    createdAt: "2026-02-16T22:49:51.225Z",
    updatedAt: "2026-02-16T22:52:58.169Z",
  },
  {
    id: 4,
    name: "Lat Pulldown",
    primaryMuscleGroup: "BACK",
    equipment: "MACHINE",
    type: "STRENGTH",
    isCustom: false,
    isActive: true,
    createdAt: "2026-02-16T22:49:51.153Z",
    updatedAt: "2026-02-16T22:52:58.097Z",
  },
  {
    id: 22,
    name: "Treadmill Jog",
    primaryMuscleGroup: "TOTAL_BODY",
    equipment: "MACHINE",
    type: "CARDIO",
    isCustom: false,
    isActive: true,
    createdAt: "2026-02-16T22:52:58.242Z",
    updatedAt: "2026-02-16T22:52:58.242Z",
  },
];

export const mockRoutines = [
  {
    id: 1,
    name: "Upper Body A",
    tags: ["push", "strength"],
    createdAt: "2026-02-17T03:33:33.272Z",
    updatedAt: "2026-02-17T03:33:33.272Z",
  },
];

export const mockSessions = [
  {
    id: 2,
    routineId: 1,
    routineNameSnapshot: "Upper Body A",
    date: "2026-02-18T07:10:31.385Z",
    completed: false,
    sessionExercises: [
      {
        id: 3,
        workoutSessionId: 2,
        exerciseId: 2,
        sectionLabel: "Strength A",
        orderIndex: 1,
        exercise: {
          id: 2,
          name: "Barbell Bench Press",
          primaryMuscleGroup: "CHEST",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: false,
          isActive: true,
          createdAt: "2026-02-16T22:49:51.007Z",
          updatedAt: "2026-02-16T22:52:57.951Z",
        },
        sessionSets: [
          {
            id: 4,
            sessionExerciseId: 3,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: 10,
            actualWeight: 15,
          },
          {
            id: 5,
            sessionExerciseId: 3,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 6,
            sessionExerciseId: 3,
            orderIndex: 2,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
      {
        id: 4,
        workoutSessionId: 2,
        exerciseId: 1,
        sectionLabel: "Strength A",
        orderIndex: 2,
        exercise: {
          id: 1,
          name: "Barbell Back Squat (Heavy)",
          primaryMuscleGroup: "QUADS",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: true,
          isActive: false,
          createdAt: "2026-02-16T22:49:50.583Z",
          updatedAt: "2026-02-17T03:18:44.485Z",
        },
        sessionSets: [],
      },
    ],
  },
  {
    id: 5,
    routineId: 1,
    routineNameSnapshot: "Upper Body A",
    date: "2026-02-18T08:52:42.587Z",
    completed: false,
    sessionExercises: [
      {
        id: 9,
        workoutSessionId: 5,
        exerciseId: 2,
        sectionLabel: "Strength A",
        orderIndex: 1,
        exercise: {
          id: 2,
          name: "Barbell Bench Press",
          primaryMuscleGroup: "CHEST",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: false,
          isActive: true,
          createdAt: "2026-02-16T22:49:51.007Z",
          updatedAt: "2026-02-16T22:52:57.951Z",
        },
        sessionSets: [
          {
            id: 13,
            sessionExerciseId: 9,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: 12,
            actualWeight: 15,
          },
          {
            id: 14,
            sessionExerciseId: 9,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: 14,
            actualWeight: 12,
          },
          {
            id: 15,
            sessionExerciseId: 9,
            orderIndex: 2,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 16,
            sessionExerciseId: 9,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 17,
            sessionExerciseId: 9,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
      {
        id: 10,
        workoutSessionId: 5,
        exerciseId: 1,
        sectionLabel: "Strength A",
        orderIndex: 2,
        exercise: {
          id: 1,
          name: "Barbell Back Squat (Heavy)",
          primaryMuscleGroup: "QUADS",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: true,
          isActive: false,
          createdAt: "2026-02-16T22:49:50.583Z",
          updatedAt: "2026-02-17T03:18:44.485Z",
        },
        sessionSets: [
          {
            id: 18,
            sessionExerciseId: 10,
            orderIndex: 2,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 20,
            sessionExerciseId: 10,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 19,
            sessionExerciseId: 10,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    routineId: 1,
    routineNameSnapshot: "Upper Body A",
    date: "2026-02-24T17:34:00.811Z",
    completed: false,
    sessionExercises: [
      {
        id: 11,
        workoutSessionId: 6,
        exerciseId: 2,
        sectionLabel: "Strength A",
        orderIndex: 1,
        exercise: {
          id: 2,
          name: "Barbell Bench Press",
          primaryMuscleGroup: "CHEST",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: false,
          isActive: true,
          createdAt: "2026-02-16T22:49:51.007Z",
          updatedAt: "2026-02-16T22:52:57.951Z",
        },
        sessionSets: [
          {
            id: 22,
            sessionExerciseId: 11,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: 12,
          },
          {
            id: 21,
            sessionExerciseId: 11,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 23,
            sessionExerciseId: 11,
            orderIndex: 2,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 25,
            sessionExerciseId: 11,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 24,
            sessionExerciseId: 11,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
      {
        id: 12,
        workoutSessionId: 6,
        exerciseId: 1,
        sectionLabel: "Strength A",
        orderIndex: 2,
        exercise: {
          id: 1,
          name: "Barbell Back Squat (Heavy)",
          primaryMuscleGroup: "QUADS",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: true,
          isActive: false,
          createdAt: "2026-02-16T22:49:50.583Z",
          updatedAt: "2026-02-17T03:18:44.485Z",
        },
        sessionSets: [
          {
            id: 26,
            sessionExerciseId: 12,
            orderIndex: 2,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 28,
            sessionExerciseId: 12,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 27,
            sessionExerciseId: 12,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    routineId: 1,
    routineNameSnapshot: "Upper Body A",
    date: "2026-02-25T16:55:45.288Z",
    completed: false,
    sessionExercises: [
      {
        id: 13,
        workoutSessionId: 7,
        exerciseId: 2,
        sectionLabel: "Strength A",
        orderIndex: 1,
        exercise: {
          id: 2,
          name: "Barbell Bench Press",
          primaryMuscleGroup: "CHEST",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: false,
          isActive: true,
          createdAt: "2026-02-16T22:49:51.007Z",
          updatedAt: "2026-02-16T22:52:57.951Z",
        },
        sessionSets: [
          {
            id: 29,
            sessionExerciseId: 13,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 30,
            sessionExerciseId: 13,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 31,
            sessionExerciseId: 13,
            orderIndex: 2,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 33,
            sessionExerciseId: 13,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 32,
            sessionExerciseId: 13,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
      {
        id: 14,
        workoutSessionId: 7,
        exerciseId: 1,
        sectionLabel: "Strength A",
        orderIndex: 2,
        exercise: {
          id: 1,
          name: "Barbell Back Squat (Heavy)",
          primaryMuscleGroup: "QUADS",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: true,
          isActive: false,
          createdAt: "2026-02-16T22:49:50.583Z",
          updatedAt: "2026-02-17T03:18:44.485Z",
        },
        sessionSets: [
          {
            id: 34,
            sessionExerciseId: 14,
            orderIndex: 2,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: 20,
            actualWeight: 15,
          },
          {
            id: 35,
            sessionExerciseId: 14,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 36,
            sessionExerciseId: 14,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
    ],
  },
  {
    id: 12,
    routineId: 1,
    routineNameSnapshot: "Upper Body A",
    date: "2026-02-25T18:17:01.371Z",
    completed: false,
    sessionExercises: [
      {
        id: 23,
        workoutSessionId: 12,
        exerciseId: 2,
        sectionLabel: "Strength A",
        orderIndex: 1,
        exercise: {
          id: 2,
          name: "Barbell Bench Press",
          primaryMuscleGroup: "CHEST",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: false,
          isActive: true,
          createdAt: "2026-02-16T22:49:51.007Z",
          updatedAt: "2026-02-16T22:52:57.951Z",
        },
        sessionSets: [
          {
            id: 70,
            sessionExerciseId: 23,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 69,
            sessionExerciseId: 23,
            orderIndex: 1,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 71,
            sessionExerciseId: 23,
            orderIndex: 2,
            targetMinReps: 8,
            targetMaxReps: 10,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 72,
            sessionExerciseId: 23,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 73,
            sessionExerciseId: 23,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
      {
        id: 24,
        workoutSessionId: 12,
        exerciseId: 1,
        sectionLabel: "Strength A",
        orderIndex: 2,
        exercise: {
          id: 1,
          name: "Barbell Back Squat (Heavy)",
          primaryMuscleGroup: "QUADS",
          equipment: "BARBELL",
          type: "STRENGTH",
          isCustom: true,
          isActive: false,
          createdAt: "2026-02-16T22:49:50.583Z",
          updatedAt: "2026-02-17T03:18:44.485Z",
        },
        sessionSets: [
          {
            id: 74,
            sessionExerciseId: 24,
            orderIndex: 2,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 76,
            sessionExerciseId: 24,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
          {
            id: 75,
            sessionExerciseId: 24,
            orderIndex: 3,
            targetMinReps: 10,
            targetMaxReps: 12,
            targetExactReps: null,
            actualReps: null,
            actualWeight: null,
          },
        ],
      },
    ],
  },
];
